name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find ZIP
        run: |
          ZIP_FILE=$(find . -maxdepth 1 -type f -name "*.zip" | head -n 1)
          echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_ENV

      - name: Extract project
        run: |
          mkdir -p app
          unzip -q "$ZIP_FILE" -d app
          PUBSPEC=$(find app -name pubspec.yaml -print -quit)
          echo "PUBSPEC=$PUBSPEC" >> $GITHUB_ENV
          echo "PROJECT_DIR=$(dirname "$PUBSPEC")" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.3"
          channel: stable

      - name: Get dependencies
        run: |
          cd "$PROJECT_DIR"
          flutter pub get

      - name: Build APK
        run: |
          cd "$PROJECT_DIR"
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KYRO-Customer-App
          path: "${{ env.PROJECT_DIR }}/build/app/outputs/flutter-apk/app-release.apk"
